### ISSUE TITLE
Change link colour in dark mode

### ISSUE THREAD

**Issue by AustinAggiss** [Crazypersonalph/HyperSEQTA#30]
### The Problem
When I am looking at links, they are by default a dark blue. If I have dark theme enabled, this becomes hard to read.
This is seems to be affected by the base theme section of the themes.css file from SEQTA. However, after modifying the CSS to have my new colour, it will work until I switch to another section. If I change it, then move to my Direqt Messages, it won't have the change until I modify the css in any way, which seems to refresh it's memory that it is supposed to be different.
```
a:not(.resource) {
	color: #204a87;
	text-decoration: underline;
	transition: text-shadow 0.5s;
}
```
### Examples
In **Direct Messages**:
<img width="231" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/d586a77f-1022-42d5-b68c-f51c6f450ee0">
In **Notices**:
<img width="468" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/3c775498-7bfc-4fdb-8e3b-e5f1e5fd0231">

### The Enhancement
I think it would be a pretty simple enhancement to be able to change this to another colour, similar to this light blue I quickly colour picked. Or even let the user select a colour that fits with their theme. I am not super familiar with JS, but I do understand most of CSS, so I don't know how to actually code it in, but this is the outcome that we should work towards I think.
<img width="462" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/b5f2ba17-1cbe-477f-a85c-58a48e863068">

**Comment by Crazypersonalph** [comment]
Will work on it, look out for commits!
Information and status updates on things will be sent through the Discord

**Comment by Crazypersonalph** [comment]
Fixed in dev and testing branches, please test it out and give feedback, so that this change can move into production.

**Comment by AustinAggiss** [comment]
### The Good News
Direct Messages are now working!
<img width="227" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/23f5e311-bde0-44a6-bf94-984b6fd784c9">
### The Bad News
Notices on the home page, and on the notices page both still use the old link colour.
<img width="464" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/6ace39e9-8790-48d3-9016-3eae896b3285">
It appears to still be this themes.css file and the same code from before according to DevTools that is setting the colour.

**Comment by Crazypersonalph** [comment]
This looks like it might soon be turning into a "won't fix" situation, I'll try looking harder for a way

**Comment by Crazypersonalph** [comment]
I'll continue tomorrow.

**Comment by AustinAggiss** [comment]
### Update
Now they look like this🤦‍♂️
<img width="455" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/3b227ea7-a8ff-4b12-8eaa-8a65f47b80d6">

**Comment by Crazypersonalph** [comment]
See #8 for more details about that (it is a long thread btw)

**Comment by Crazypersonalph** [comment]
https://github.com/Crazypersonalph/betterseqta/issues/8#issuecomment-1545661809

**Comment by Crazypersonalph** [comment]
Looks like my fix is working???
Another issue to solve.

**Comment by AustinAggiss** [comment]
I'll close this issue for now since it is an issue as part of #8 as pointed out by @Crazypersonalph.
