### ISSUE TITLE
Homepage course and assessment links no longer functional

### ISSUE THREAD

**Issue by AustinAggiss** [Crazypersonalph/HyperSEQTA#32]
### The Problem
The buttons to take you to a subjects assessment page and courses page are broken, as they no longer work.
<img width="49" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/37136442/80de5545-becb-440c-affa-abbe177262d2">

**Comment by Crazypersonalph** [comment]
Time to take a look through commit history :smiling_face_with_tear:

**Comment by Crazypersonalph** [comment]
Found the issue, it is with DOMPurify, I am guessing that the call to redirect the buttons to the certain pages is using the stringToHTML function, and the the buttons are passing script tags, or other potentially dangerous tags, so as a result, the buttons stopped working.

Also good evening fellow perthian.

**Comment by Crazypersonalph** [comment]
Yeah, ```location.href='../#?page=/assessments/5051:99672'``` is probably getting filtered out.

**Comment by Crazypersonalph** [comment]
Yeah, looks like ```location.href='../#?page=/assessments/numbershere:numbershere'``` is getting filtered out within DOMPurify.

**Comment by Crazypersonalph** [comment]
Will take a further look at it tomorrow, trying to find a workaround without compromising security.

**Comment by Crazypersonalph** [comment]
Just wait for merge into testing and production, we want to iron out any possible bugs that might arise, help by testing.

**Comment by AustinAggiss** [comment]
Confirmed the bug is now fixed with the latest commit, I can now use both of these without issue.
