### ISSUE TITLE
Custom JS Injection?

### ISSUE THREAD

**Issue by Dispatch9001** [Crazypersonalph/HyperSEQTA#35]
Hey!

I currently use this extension from a SEQTA PWA running in Ungoogled Chromium on my laptop running Linux. I do this because my main browser is Firefox, but I didn't want the extension loaded in my main browser (mainly for fingerprinting).

I realised that it will be a lot more friendly to my resources if I run my PWAs through the Gnome Web WebApps, and I have already migrated my others there. The only problem is SEQTA, since Web's extension support is incredibly poor. It does have the option to inject custom JS & CSS into a web app, so I was wondering if there is a way to put the core functionality of this extension into one JS script I can inject. 

I know this is an oddly specific request, and I am probably the only person who will ever use this, but any help will be greatly appreciated.

**Comment by Crazypersonalph** [comment]
Another Linux user!
Thanks for the suggestion, I'll look into it

**Comment by Dispatch9001** [comment]
Thanks!

**Comment by Crazypersonalph** [comment]
Good afternoon,
I was wondering if with Gnome WebApps, they could be able to pull down scripts from the internet
If they could, it would just be a matter of just importing github raw links into a js file and calling it a day

Kind Regards

**Comment by Dispatch9001** [comment]
![image](https://github.com/Crazypersonalph/betterseqta/assets/111946536/951992fd-9b09-40cc-93df-52d1c182ad53)

So, when using custom JS it lets you edit one file that is empty by default. Could you send me a test script that will pull down something, so we can see if it works? 

I would do it myself, but honestly I am pretty clueless with Javascript, my coding knowledge doesn't go far past simple Bash scripts I make for convenience lol.

**Comment by Crazypersonalph** [comment]
Shouldn't the WebApp just open in your default browser; it should load your extensions anyway?
You might be able to try looking for an option to turn on extensions

Personally, I don't use GNOME, I use sway, so I don't actually know how GNOME does this.

Creating a specific file for this would be a little bit annoying, as some of the stuff that BetterSeqta does has certain file paths hardcoded, stuff like that, etc;

Kind Regards

**Comment by Crazypersonalph** [comment]
You might be able to get away with copying the code in Seqta.js, changing some parts within it, and doing the same for the css files, but I do not believe you could actually encapsulate BetterSeqta as a whole.

I know this isn't ideal, but it is the best answer I can give
Thanks

**Comment by ghost** [comment]
What about bookmarklets? It's a bookmark that can run javascript straight into the website open. It's a great way to get around extension problems

**Comment by Crazypersonalph** [comment]
> What about bookmarklets? It's a bookmark that can run javascript straight into the website open. It's a great way to get around extension problems

The suggestion specifies using PWAs, I'm not sure if this would work

**Comment by Crazypersonalph** [comment]
We might be able to make a script which only contains the injection part of BetterSeqta, but a) It would be pretty impractical to pick apart the code and see what could/couldn't be added to the script  and b) we would have to hardcode any configurations

How do you envision this happening (how do you want this to happen)? @Dispatch9001 
Kind Regards

**Comment by norangeflame** [comment]
Is this sort of like TamperMonkey?

**Comment by Dispatch9001** [comment]
Hey @Crazypersonalph 
Thanks for bearing with me so far. 

> Shouldn't the WebApp just open in your default browser; it should load your extensions anyway?

No, Gnome's WebApps actually load in the Gnome Web (aka Epiphany) browser. The functionality is part of the browser, not Gnome itself, so you can try it on your Sway setup if you want (also, respect for using Sway, I used to use it but moved to Gnome for a more supported setup, at the time I was getting tired of tinkering, and now here I am tinkering the crap out of everything I can again lol). Gnome Web was planned to receive WebExtention support, but it never got past an alpha state and very few extensions work.

> What about bookmarklets? It's a bookmark that can run javascript straight into the website open. It's a great way to get around extension problems

That would in practice be a less practical equivalent of the already available custom JS in Epiphany or Tampermonkey. I would still be happy if thats how this ended up, but I am not sure if it is the best solution.

> How do you envision this happening

At its core, it just needs to combine all (or most of the core) scripts into 1 JS file. This could in practice just be one small JS file that automatically imports all the others from a GitHub raw URL, at least from my limited understanding of Javascript. That would make it usable for me on Gnome Web, and also anyone who uses Tamper Monkey. iirc some Android browsers also support Tampermonkey now, so it could even lead to some level of mobile support.

**Comment by Crazypersonalph** [comment]
We’re actually implementing new webpack stuff now for dependency reasons, you might be able to use the bundle for this purpose, hopefully

**Comment by Crazypersonalph** [comment]
Closed for inactivity

**Comment by Crazypersonalph** [comment]
Closed for inactivity
