### ISSUE TITLE
Notices in home page don't follow filters as the notices page

### ISSUE THREAD

**Issue by ghost** [Crazypersonalph/HyperSEQTA#41]
I have these filters on the notices page (also the tick is the wrong colour but that's part of #40 )

![image](https://github.com/Crazypersonalph/betterseqta/assets/81658610/b6121322-0fab-4805-8c62-89b6505cc733)

But when I look at the notices in the home page you can see stuff that you shouldn't with the filters

![image](https://github.com/Crazypersonalph/betterseqta/assets/81658610/1440a431-6b7a-4b79-a1c0-64b80408d025)

**Comment by norangeflame** [comment]
Good find. I will add it to #40, which I'm going to use as an ongoing bug list.

**Comment by ghost** [comment]
Any work on the first problem?

**Comment by Crazypersonalph** [comment]
> Any work on the first problem?

Even though its been some time since I've worked on this project, full filter support was left almost finished.

I'll work on it on the weekend, hopefully finish it off 🙂

**Comment by ghost** [comment]
Thanks for all the help.

**Comment by Crazypersonalph** [comment]
Finished this (finally after a long time of procrastination)
There is a separate date filter on the home page, labels are shared with the notices page.

Pushed into dev c0116aa

**Comment by ghost** [comment]
Thank you
