### ISSUE TITLE
Wow. Nice job!

### ISSUE THREAD

**Issue by SethBurkart123** [Crazypersonalph/HyperSEQTA#44]
I was working on a fork of my own, but I am really liking some of the code splitting that you have achieved. I started organising my repository (https://github.com/SethBurkart123/EvenBetterSEQTA) with webpack, but it looks like you are way ahead of me!

The few things that I have already done in my repository:
- Improve styling (majorly)
- Add a secondary colour for the colour picker (automagically selected)
- Fixed a whole bunch of bugs
- Migrated to manifest V3
- Rewrote the Readme
- Etc.

I would love to see if we could work together to actually clean up the code, but also make seqta actually usable!

**Comment by SethBurkart123** [comment]
<img width="924" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/108050083/9c60ae03-311a-4c38-ac1e-12ecc5446e41">
We also have official permission to put it up.

**Comment by ghost** [comment]
Do we have access to the original extension? Otherwise we would need to move everyone over to the new one which will be quite hard to do.

**Comment by SethBurkart123** [comment]
@proJM-Coding Yeah, I don't have access to it. But maybe we could convince Nulkem to give us some access to post updates? IDK, just an idea.

But otherwise it will be quite challenging. That's why I have been working on a visual overhaul on my extension fork, also some good images on the actual chrome web store might convince some people to switch.
<img width="1217" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/108050083/1cd52a5b-e849-40c0-8ea1-7fa0cb736c25">

**Comment by Crazypersonalph** [comment]
Closed because there is not really an issue, although thank you!
