### ISSUE TITLE
Certain notifications cannot be deleted.

### ISSUE THREAD

**Issue by SethBurkart123** [Crazypersonalph/HyperSEQTA#48]
When receiving a new message in SEQTA that has a long subject line with links (I haven't tested with long words though), the notifications panel can break and have the remove button disappear entirely.

<img width="381" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/108050083/1789486f-e23e-40e3-8bba-8e9b14283973">
<img width="658" alt="image" src="https://github.com/Crazypersonalph/betterseqta/assets/108050083/ce51515d-b1d5-4be8-9e04-189598e5960c">

**Comment by Crazypersonalph** [comment]
I can't seem to reproduce this issue, which branch are you on?

**Comment by Crazypersonalph** [comment]
Any update???

What version (fork) of BetterSeqta, your system specs, which branch, etc.

**Comment by Crazypersonalph** [comment]
Stale issue

**Comment by ghost** [comment]
I can say I have never had this bug even though I have been using BetterSeqta for over a year and Seqta for 3 years.
