### ISSUE TITLE
Animated Background is Cool but also Really Annoying

### ISSUE THREAD

**Issue by UnklRckrl** [Crazypersonalph/HyperSEQTA#49]
Please add an option to somehow slow down the animated background as it's cool but gets distracting from how fast it moves. Thanks!

**Comment by norangeflame** [comment]
@Crazypersonalph Relevant CSS in injected.css is line 282, line 297, line 302, where you change the "animation" element and "animation-duration" element.

**Comment by Crazypersonalph** [comment]
Just saw the issue request now, I'll implement a slider to change the animation speed.

**Comment by ghost** [comment]
There is an existing toggle but a speed slider would be nice

**Comment by Crazypersonalph** [comment]
Completed in commit d43ebd3
