### ISSUE TITLE
Just some info for you

### ISSUE THREAD

**Issue by ghost** [Crazypersonalph/HyperSEQTA#54]
Today I was brought aware of a project called BetterSEQTA+
Here is the extention page: [https://chrome.google.com/webstore/detail/betterseqta%2B/afdgaoaclhkhemfkkkonemoapeinchel?utm_source=chrome-app-launcher-search](https://chrome.google.com/webstore/detail/betterseqta%2B/afdgaoaclhkhemfkkkonemoapeinchel?utm_source=chrome-app-launcher-search)
and the repo: [https://github.com/SethBurkart123/evenbetterseqta](https://github.com/SethBurkart123/evenbetterseqta)
I think you should take a look.

**Comment by Crazypersonalph** [comment]
Yeah it is the one by SethBurkart

**Comment by ghost** [comment]
There are some ideas that he has made that I think could be added to HyperSEQTA. Just thought it's worth a look.
