### ISSUE TITLE
Notices/DMs with rich text (?) are broken

### ISSUE THREAD

**Issue by Crazypersonalph** [Crazypersonalph/HyperSEQTA#8]
https://github.com/Nulkem/betterseqta/issues/17

https://github.com/Nulkem/betterseqta/issues/22

**Comment by norangeflame** [comment]
I'm noticing that notices containing tables are not displayed properly (or at all) on the home page, but they are fine on the notices page.

**Comment by Crazypersonalph** [comment]
> I'm noticing that notices containing tables are not displayed properly (or at all) on the home page, but they are fine on the notices page.

Could you please explain further, preferably with screenshots, error messages, code etc?

I just need some further clarification on whether this is with rich text, on the notices page, in dms, etc.

**Comment by norangeflame** [comment]
Ok so I'm not really that good at JavaScript but with a bit of help from ChatGPT I fixed all of _my_ broken notices. No idea if it will work for you. 
Basically my broken notices were notices that contained tables of information, and in the BetterSEQTA home page they weren't displaying the tables at all (the tables should have had sporting info, team members etc.). 
I had another broken notice but it's gone now, and I figured out the reason it was broken is a SEQTA bug not a BetterSEQTA bug - the notice has a bunch of empty "p" tags.

**Comment by norangeflame** [comment]
The issue that was opened on the BetterSEQTA page looks more like a formatting issue, unfortunately my notices are fine so I can't troubleshoot.

**Comment by norangeflame** [comment]
Regarding your DM issue, I have a similar issue for messages that are sent from SEQTA Teach. Most of my messages are normal but occasionally if a teacher sends us a DM that also goes to our Outlook school emails, it looks broken and hard to read.

Normal: 
![Screenshot 2023-05-06 133148](https://user-images.githubusercontent.com/106525819/236602401-7bb8b164-62fa-46d3-9fa0-f4b28dd78950.png)


With BetterSEQTA on:
![Screenshot 2023-05-06 133044](https://user-images.githubusercontent.com/106525819/236602363-dd0c7f17-6262-43f7-bc63-7a587a6fd582.png)

**Comment by Crazypersonalph** [comment]
The p tags are paragraph tags btw, I'm not sure why they are being created.

I believe Seqta might be using them in its formatting to separate up the table, which is obviously not the best practice, I'll look further into it

Also now I have figured that the weird font issue not just with me, I'll look further into that as well

**Comment by norangeflame** [comment]
> The p tags are paragraph tags btw, I'm not sure why they are being created.
> 
> I believe Seqta might be using them in its formatting to separate up the table, which is obviously not the best practice, I'll look further into it

Yeah, there are a bunch of the "p" tags before one of the tables in this notice: 
![image](https://user-images.githubusercontent.com/106525819/236609599-85f4d616-31ee-442b-8aad-2c0f2766f48b.png)

**Comment by norangeflame** [comment]
@Crazypersonalph minor changes to SEQTA.js @ lines 30-40 and 3054-3058: https://github.com/norangeflame/betterseqta. 
These changes fix all of my Notices formatting issues when Notices are displayed on the Home page of BetterSEQTA.
Got exams coming up so I'll look at other bugs in 3-4 weeks.

**Comment by Crazypersonalph** [comment]
Do you wanna create a pull request and I'll review it

**Comment by Crazypersonalph** [comment]
Changes look good so far, great job!
I'll work on modularizing the code over the next few weeks, should improve maintainability and readability
Thanks

**Comment by Crazypersonalph** [comment]
Looks like if we make some changes to some extra parts of the code (not included in your commit) we can make the old stringToHTML function redundant as a whole

**Comment by norangeflame** [comment]
Well originally I modified the old stringToHTML but that broke BetterSEQTA because there were other parts that used it, so that's why I made a separate function. 
If you still would like a pull request, is there a way to do it without including my changes to my readme file or will you just ignore that change?

**Comment by Crazypersonalph** [comment]
Best practice would be creating a new branch with only the bug fix changes, it would have been preferable if you cloned my repo rather than Nulkem's, it removes some merge conflicts that may occur.

**Comment by norangeflame** [comment]
Done (I think)

**Comment by norangeflame** [comment]
2 things: 
Your modified code unfortunately doesn't work (when I download and test code as extension). I tested your code alongside a separate browser with the original BetterSEQTA and there seemed to be no difference (still broken notices)
Even with my code I've found more formatting issues (new notices that I obviously hadn't encountered yet)

Your modified version of mine:
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/105a1633-abfa-4e9e-b047-ef80e8ed65b5)

My original edit:
![Screenshot 2023-05-12 202042](https://github.com/Crazypersonalph/betterseqta/assets/106525819/e9ab9fd7-1112-44f2-bfe1-e5b52adf4f3f)

Maybe your notices are different and so you couldn't see this formatting issue?

**Comment by Crazypersonalph** [comment]
Interesting, I'll have another look into it

It should be working, it is exactly your code, except made to fit into 1 function

I personally don't have this issue, so I'm not able to test it 😅

**Comment by Crazypersonalph** [comment]
> 2 things: Your modified code unfortunately doesn't work (when I download and test code as extension). I tested your code alongside a separate browser with the original BetterSEQTA and there seemed to be no difference (still broken notices) Even with my code I've found more formatting issues (new notices that I obviously hadn't encountered yet)
> 
> Your modified version of mine: ![image](https://user-images.githubusercontent.com/106525819/237969219-105a1633-abfa-4e9e-b047-ef80e8ed65b5.png)
> 
> My original edit: ![Screenshot 2023-05-12 202042](https://user-images.githubusercontent.com/106525819/237969375-e9ab9fd7-1112-44f2-bfe1-e5b52adf4f3f.png)
> 
> Maybe your notices are different and so you couldn't see this formatting issue?

Could you please try using an earlier commit, that doesn't include the DOMPurify section, but does include my patch?

There was a pretty serious vulnerability patched there, I want to see if the patch is the issue; It is working fine on my system.

**Comment by Crazypersonalph** [comment]
Please try reverting to this commit,
https://github.com/Crazypersonalph/betterseqta/commit/4d831e7fddbd045727aa6da9d5fe5e9b524611bd

**Comment by norangeflame** [comment]
The code I tested did not yet have the DOMPurify section. I tested that commit anyway and it still didn't work.

**Comment by norangeflame** [comment]
> Regarding your DM issue, I have a similar issue for messages that are sent from SEQTA Teach. Most of my messages are normal but occasionally if a teacher sends us a DM that also goes to our Outlook school emails, it looks broken and hard to read.
> 
> Normal: ![Screenshot 2023-05-06 133148](https://user-images.githubusercontent.com/106525819/236602401-7bb8b164-62fa-46d3-9fa0-f4b28dd78950.png)
> 
> With BetterSEQTA on: ![Screenshot 2023-05-06 133044](https://user-images.githubusercontent.com/106525819/236602363-dd0c7f17-6262-43f7-bc63-7a587a6fd582.png)

I think I've found the issue here:
The weird text is caused by the text-shadow property
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/79d68af8-0d7d-4112-9e4c-4b166aacfea1)


The weird boxes seem to be the result of some BetterSEQTA CSS that sets table outlines to a certain colour, as that entire message is contained within multiple tables. Turning the following properties off (deselecting in devtools) fixes it:
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/af3ca83c-888e-4f0f-9577-9eacc506f415)
However the message is still in "light mode" and so requires some more code to match it to the BetterSEQTA colours.

**Comment by Crazypersonalph** [comment]
Thank you for the insight!

I'm not really a front-end type guy, more so a back-end, dev ops, sysadmin, pentesting guy, let alone a chrome extension developer

Sometimes these things go over my head lol

**Comment by Crazypersonalph** [comment]
> > Regarding your DM issue, I have a similar issue for messages that are sent from SEQTA Teach. Most of my messages are normal but occasionally if a teacher sends us a DM that also goes to our Outlook school emails, it looks broken and hard to read.
> > Normal: ![Screenshot 2023-05-06 133148](https://user-images.githubusercontent.com/106525819/236602401-7bb8b164-62fa-46d3-9fa0-f4b28dd78950.png)
> > With BetterSEQTA on: ![Screenshot 2023-05-06 133044](https://user-images.githubusercontent.com/106525819/236602363-dd0c7f17-6262-43f7-bc63-7a587a6fd582.png)
> 
> I think I've found the issue here: The weird text is caused by the text-shadow property ![image](https://user-images.githubusercontent.com/106525819/238104346-79d68af8-0d7d-4112-9e4c-4b166aacfea1.png)
> 
> The weird boxes seem to be the result of some BetterSEQTA CSS that sets table outlines to a certain colour, as that entire message is contained within multiple tables. Turning the following properties off (deselecting in devtools) fixes it: ![image](https://user-images.githubusercontent.com/106525819/238104474-af3ca83c-888e-4f0f-9577-9eacc506f415.png) However the message is still in "light mode" and so requires some more code to match it to the BetterSEQTA colours.

Using this information, I am now constructing a patch, the issue is within the CSS injection in inject/injected.css

**Comment by Crazypersonalph** [comment]
It also seems as though your border box issue is not actually an issue with BetterSeqta, it is an issue within BetterSeqta itself.

This problem within Seqta itself can be fixed through BetterSeqta though.

**Comment by Crazypersonalph** [comment]
@norangeflame Try pulling from the dev branch and test out the new patches

**Comment by norangeflame** [comment]
Weird shadowy text is fixed, but I think the text was white and so the only reason it was visible was because of the shadow behind it, now that the shadow is removed the text should be set to black (or any visible colour). Body text is fine by footer text and title aren't visible. Nice job so far though.
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/41986c96-86b7-4a2c-b71f-a2b23076b084)

**Comment by Crazypersonalph** [comment]
> Weird shadowy text is fixed, but I think the text was white and so the only reason it was visible was because of the shadow behind it, now that the shadow is removed the text should be set to black (or any visible colour). Body text is fine by footer text and title aren't visible. Nice job so far though. ![image](https://user-images.githubusercontent.com/106525819/238110224-41986c96-86b7-4a2c-b71f-a2b23076b084.png)

There is a slight issue with changing the colour of the text, it is that it affects other things such as DMs

Anything with non-rich text will be affected with the change of colour, causing a lot of unwanted side effects

Our best bet would be trying to converting everything to the black scheme, so there wouldn't be collisions

Feel free to join the Discord so we can discuss this further

**Comment by Crazypersonalph** [comment]
Checklist:
Fix shadow issue: ✅
Notice Issue: Working on it
DM issue, related to the shadow issue: ✅

**Comment by Crazypersonalph** [comment]
I'll assign it to help wanted, just for now, as I am quite busy right now.

**Comment by Crazypersonalph** [comment]
I have an interesting development:
It seems that the issue with the colour of links in notices seems to be a bit on and off

In some notices, the colour is normal, and in others, it is the darker colour that is hard to see
Thanks

**Comment by Crazypersonalph** [comment]
Pushed to dev.
Keep in mind there may be a few issues with this patch, I haven't exactly thoroughly tested it yet, but that's why there is a dev branch after all!

Thank you
P.S. This took way too long to make
